# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
release:
  prerelease: auto
builds:
- env:
  - CGO_ENABLED=0
  main: cmd/mqtt2prometheus.go
  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux.
  goos:
    - linux
    - darwin
    - freebsd
    - windows

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64
    - 386
    - riscv64
    - ppc64le
    - s390x

  # GOARM to build for when GOARCH is arm.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Default is only 6.
  goarm:
    - 5
    - 6
    - 7

  # GOMIPS and GOMIPS64 to build when GOARCH is mips, mips64, mipsle or mips64le.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Default is empty.
  gomips:
    - hardfloat
    - softfloat
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:

  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: amd64
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-amd64"
      - "hikhvar/mqtt2prometheus:latest-amd64"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-amd64"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-amd64"

  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: arm64
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm64"
    image_templates:
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-arm64"
      - "hikhvar/mqtt2prometheus:latest-arm64"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-arm64"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-arm64"

  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: arm
    goarm: 6
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm/v6"
    image_templates:
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-arm6"
      - "hikhvar/mqtt2prometheus:latest-arm6"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-arm6"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-arm6"

  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: arm
    goarm: 6
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm/v6"
    image_templates:
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-arm6"
      - "hikhvar/mqtt2prometheus:latest-arm6"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-arm6"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-arm6"

  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: arm
    goarm: 7
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm/v7"
    image_templates:
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-arm7"
      - "hikhvar/mqtt2prometheus:latest-arm7"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-arm7"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-arm7"

  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: 386
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/386"
    image_templates:
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-386"
      - "hikhvar/mqtt2prometheus:latest-386"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-386"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-386"

  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: riscv64
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/riscv64"
    image_templates:
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-riscv64"
      - "hikhvar/mqtt2prometheus:latest-riscv64"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-riscv64"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-riscv64"

docker_manifests:
  # Docker Registry
  - name_template: hikhvar/mqtt2prometheus:{{ .Tag }}
    image_templates:
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-amd64"
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-arm64"
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-arm6"
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-arm7"
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-riscv64"
      - "hikhvar/mqtt2prometheus:{{ .Tag }}-386"

  - name_template: hikhvar/mqtt2prometheus:latest
    image_templates:
      - "hikhvar/mqtt2prometheus:latest-amd64"
      - "hikhvar/mqtt2prometheus:latest-arm64"
      - "hikhvar/mqtt2prometheus:latest-arm6"
      - "hikhvar/mqtt2prometheus:latest-arm7"
      - "hikhvar/mqtt2prometheus:latest-riscv64"
      - "hikhvar/mqtt2prometheus:latest-386"

  # Github Registry
  - name_template: ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}
    image_templates:
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-amd64"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-arm64"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-arm6"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-arm7"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-riscv64"
      - "ghcr.io/hikhvar/mqtt2prometheus:{{ .Tag }}-386"
  - name_template: ghcr.io/hikhvar/mqtt2prometheus:latest
    image_templates:
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-amd64"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-arm64"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-arm6"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-arm7"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-riscv64"
      - "ghcr.io/hikhvar/mqtt2prometheus:latest-386"